[#ftl]
[#--template for the client-side enum type.--]
// Generated by xsd compiler for swift/ios
// DO NOT CHANGE!

enum ${projectPrefix}${enum.name} {
[#list enum.enumConstants as constant]
    case ${constant.name}
[/#list]
}