[#ftl]
[#--template for the client class.--]
// Generated by xsd compiler for typescript
// DO NOT CHANGE!

module ${namespace} {

    export interface ${clazz.name} [#if clazz.superClass??]extends ${clazz.superClass.name} [/#if]{

        [#list clazz.fields as field]
        [#compress]
        [#if field.value??]
            [#if field.type.primitive]
                [#assign value = "${field.value}"]
            [#else]
                [#assign value = "\"${field.value}\""]
            [/#if]
        [/#if]
        [#if field.type.collection]
            [#assign type = field.type.typeParameters?first]
            [#assign fieldTypeName = "${type.name}[]"]
        [#else]
            [#assign fieldTypeName = "${field.type.name}"]
        [/#if]
        [/#compress]

        ${field.name}: ${fieldTypeName} [#if field.value??]= ${value}[/#if];

        [/#list]
    }
}