[#ftl]
[#--template for the client-side enum declaration.--]
// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

[#if enum.persistentEnum]
  [#assign keyword = "RLM"]
[#else]
  [#assign keyword = ""]
[/#if]

#import <Foundation/Foundation.h>
#import "${projectPrefix}${keyword}Enum.h"

@class ${projectPrefix}${enum.name};

[#if enum.docComment??]
/**
 @file
 ${enum.docComment?chop_linebreak?replace("\n", "\n ")?replace("\t", "")}

*/
[/#if]
  [#list enum.enumConstants as constant]

  [#if constant.docComment??]
/**
 ${constant.docComment?replace("\n", "\n ")?replace("\t", "")}
*/
  [/#if]
extern ${projectPrefix}${enum.name} * ${enum.name?upper_case}_${constant.name?upper_case};
  [/#list]

typedef NS_ENUM (NSInteger, ${enum.name}Type) {
[#list enum.enumConstants as constant]
${enum.name}_${constant.name?capitalize},
[/#list]
};

@interface ${projectPrefix}${enum.name} : ${projectPrefix}${keyword}Enum

@end