// Generated by xsd compiler for ios/objective-c
// DO NOT CHANGE!

#import <CocoaLumberjack/CocoaLumberjack.h>

#define LOG_LEVEL_DEF ddLogLevel
#define LOG_ASYNC_ENABLED YES

#ifdef DEBUG
static const int ddLogLevel = DDLogLevelDebug;
#else
static const int ddLogLevel = DDLogLevelOff;
#endif