[#ftl]
[#--template for the client class.--]
// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ${clazz.packageName};

import java.io.Serializable;
[#list imports as import]
import ${import};
[/#list]

import com.google.gson.annotations.SerializedName;

[#if clazz.docComment??]
/**
 * ${clazz.docComment?replace("\n", "\n * ")?replace("\t", "")}
 */
[/#if]

public [#if clazz.abstract]abstract [/#if]class ${clazz.name} [#if clazz.superClass??]extends ${clazz.superClass.name} [/#if]implements Serializable {

    private static final long serialVersionUID = -1L;

    [#list clazz.fields as field]
    [#if field.modifiedName]
    @SerializedName("${field.initialName}")[/#if]
	public ${field.type.name} ${field.name};
	
    [/#list]
}