[#ftl]
[#--template for the client-side enum _type.--]
// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package ${enum.packageName};

[#if enum.docComment??]
/**
 * ${enum.docComment?chop_linebreak?replace("\n", "\n * ")?replace("\t", "")}
 */
[/#if]
public enum ${enum.name} {
  [#list enum.enumConstants as constant]

  [#if constant.docComment??]
    /**
     * ${constant.docComment?replace("\n", "\n   * ")?replace("\t", "")}
     */
  [/#if]
    ${constant.value?replace("\\s", "_")}[#if constant_has_next],[#else];[/#if]
  
  [/#list]
  
}